/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayInInstruction from './PayInInstruction';
import Quote from './Quote';

/**
 * The AcceptedQuote model module.
 * @module model/AcceptedQuote
 * @version 1.0.1
 */
class AcceptedQuote {
    /**
     * Constructs a new <code>AcceptedQuote</code>.
     * @alias module:model/AcceptedQuote
     */
    constructor() { 
        
        AcceptedQuote.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AcceptedQuote</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AcceptedQuote} obj Optional instance to populate.
     * @return {module:model/AcceptedQuote} The populated <code>AcceptedQuote</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AcceptedQuote();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = Quote.constructFromObject(data['quote']);
            }
            if (data.hasOwnProperty('payInInstruction')) {
                obj['payInInstruction'] = PayInInstruction.constructFromObject(data['payInInstruction']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AcceptedQuote</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AcceptedQuote</code>.
     */
    static validateJSON(data) {
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          Quote.validateJSON(data['quote']);
        }
        // validate the optional field `payInInstruction`
        if (data['payInInstruction']) { // data not null
          PayInInstruction.validateJSON(data['payInInstruction']);
        }

        return true;
    }


}



/**
 * @member {module:model/Quote} quote
 */
AcceptedQuote.prototype['quote'] = undefined;

/**
 * @member {module:model/PayInInstruction} payInInstruction
 */
AcceptedQuote.prototype['payInInstruction'] = undefined;






export default AcceptedQuote;

