/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidationErrorDto from './ValidationErrorDto';

/**
 * The ClientValidationErrorDto model module.
 * @module model/ClientValidationErrorDto
 * @version 1.0.1
 */
class ClientValidationErrorDto {
    /**
     * Constructs a new <code>ClientValidationErrorDto</code>.
     * List of validation errors
     * @alias module:model/ClientValidationErrorDto
     */
    constructor() { 
        
        ClientValidationErrorDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ClientValidationErrorDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ClientValidationErrorDto} obj Optional instance to populate.
     * @return {module:model/ClientValidationErrorDto} The populated <code>ClientValidationErrorDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ClientValidationErrorDto();

            if (data.hasOwnProperty('errorList')) {
                obj['errorList'] = ApiClient.convertToType(data['errorList'], [ValidationErrorDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ClientValidationErrorDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ClientValidationErrorDto</code>.
     */
    static validateJSON(data) {
        if (data['errorList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['errorList'])) {
                throw new Error("Expected the field `errorList` to be an array in the JSON data but got " + data['errorList']);
            }
            // validate the optional field `errorList` (array)
            for (const item of data['errorList']) {
                ValidationErrorDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/ValidationErrorDto>} errorList
 */
ClientValidationErrorDto.prototype['errorList'] = undefined;






export default ClientValidationErrorDto;

