/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MerchantIdCreateRequestWallet model module.
 * @module model/MerchantIdCreateRequestWallet
 * @version 1.0.1
 */
class MerchantIdCreateRequestWallet {
    /**
     * Constructs a new <code>MerchantIdCreateRequestWallet</code>.
     * @alias module:model/MerchantIdCreateRequestWallet
     */
    constructor() { 
        
        MerchantIdCreateRequestWallet.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantIdCreateRequestWallet</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantIdCreateRequestWallet} obj Optional instance to populate.
     * @return {module:model/MerchantIdCreateRequestWallet} The populated <code>MerchantIdCreateRequestWallet</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantIdCreateRequestWallet();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantIdCreateRequestWallet</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantIdCreateRequestWallet</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * The ID of the wallet to link to the merchant ID.
 * @member {String} id
 * @default '501098'
 */
MerchantIdCreateRequestWallet.prototype['id'] = '501098';






export default MerchantIdCreateRequestWallet;

