/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WalletDto from './WalletDto';

/**
 * The MerchantDto model module.
 * @module model/MerchantDto
 * @version 1.0.1
 */
class MerchantDto {
    /**
     * Constructs a new <code>MerchantDto</code>.
     * @alias module:model/MerchantDto
     */
    constructor() { 
        
        MerchantDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantDto} obj Optional instance to populate.
     * @return {module:model/MerchantDto} The populated <code>MerchantDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('displayName')) {
                obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('webhookUrl')) {
                obj['webhookUrl'] = ApiClient.convertToType(data['webhookUrl'], 'String');
            }
            if (data.hasOwnProperty('autoConvertInvalidPayments')) {
                obj['autoConvertInvalidPayments'] = ApiClient.convertToType(data['autoConvertInvalidPayments'], 'Boolean');
            }
            if (data.hasOwnProperty('defaultExpiryMinutes')) {
                obj['defaultExpiryMinutes'] = ApiClient.convertToType(data['defaultExpiryMinutes'], 'Number');
            }
            if (data.hasOwnProperty('webhookVersion')) {
                obj['webhookVersion'] = ApiClient.convertToType(data['webhookVersion'], 'Number');
            }
            if (data.hasOwnProperty('wallet')) {
                obj['wallet'] = WalletDto.constructFromObject(data['wallet']);
            }
            if (data.hasOwnProperty('emailRecipients')) {
                obj['emailRecipients'] = ApiClient.convertToType(data['emailRecipients'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['displayName'] && !(typeof data['displayName'] === 'string' || data['displayName'] instanceof String)) {
            throw new Error("Expected the field `displayName` to be a primitive type in the JSON string but got " + data['displayName']);
        }
        // ensure the json data is a string
        if (data['secret'] && !(typeof data['secret'] === 'string' || data['secret'] instanceof String)) {
            throw new Error("Expected the field `secret` to be a primitive type in the JSON string but got " + data['secret']);
        }
        // ensure the json data is a string
        if (data['webhookUrl'] && !(typeof data['webhookUrl'] === 'string' || data['webhookUrl'] instanceof String)) {
            throw new Error("Expected the field `webhookUrl` to be a primitive type in the JSON string but got " + data['webhookUrl']);
        }
        // validate the optional field `wallet`
        if (data['wallet']) { // data not null
          WalletDto.validateJSON(data['wallet']);
        }
        // ensure the json data is a string
        if (data['emailRecipients'] && !(typeof data['emailRecipients'] === 'string' || data['emailRecipients'] instanceof String)) {
            throw new Error("Expected the field `emailRecipients` to be a primitive type in the JSON string but got " + data['emailRecipients']);
        }

        return true;
    }


}



/**
 * The ID of the Merchant ID.
 * @member {Number} id
 */
MerchantDto.prototype['id'] = undefined;

/**
 * The Merchant ID as a UUID.
 * @member {String} merchantId
 */
MerchantDto.prototype['merchantId'] = undefined;

/**
 * The name of the merchant displayed on the payments page.
 * @member {String} displayName
 */
MerchantDto.prototype['displayName'] = undefined;

/**
 * The secret key used to validate webhooks.
 * @member {String} secret
 */
MerchantDto.prototype['secret'] = undefined;

/**
 * The webhooks URL that webhoosk are sent to.
 * @member {String} webhookUrl
 */
MerchantDto.prototype['webhookUrl'] = undefined;

/**
 * Is set to auto convert invalid payments.
 * @member {Boolean} autoConvertInvalidPayments
 * @default true
 */
MerchantDto.prototype['autoConvertInvalidPayments'] = true;

/**
 * The default number of minutes before a payment expires for this Merchant ID.
 * @member {Number} defaultExpiryMinutes
 */
MerchantDto.prototype['defaultExpiryMinutes'] = undefined;

/**
 * The version of webhooks sent.
 * @member {Number} webhookVersion
 */
MerchantDto.prototype['webhookVersion'] = undefined;

/**
 * @member {module:model/WalletDto} wallet
 */
MerchantDto.prototype['wallet'] = undefined;

/**
 * The recipients of event emails.
 * @member {String} emailRecipients
 */
MerchantDto.prototype['emailRecipients'] = undefined;






export default MerchantDto;

