/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetworkFeeDto model module.
 * @module model/NetworkFeeDto
 * @version 1.0.1
 */
class NetworkFeeDto {
    /**
     * Constructs a new <code>NetworkFeeDto</code>.
     * @alias module:model/NetworkFeeDto
     */
    constructor() { 
        
        NetworkFeeDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetworkFeeDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkFeeDto} obj Optional instance to populate.
     * @return {module:model/NetworkFeeDto} The populated <code>NetworkFeeDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkFeeDto();

            if (data.hasOwnProperty('paidCurrency')) {
                obj['paidCurrency'] = ApiClient.convertToType(data['paidCurrency'], 'String');
            }
            if (data.hasOwnProperty('paidAmount')) {
                obj['paidAmount'] = ApiClient.convertToType(data['paidAmount'], 'Number');
            }
            if (data.hasOwnProperty('displayCurrency')) {
                obj['displayCurrency'] = ApiClient.convertToType(data['displayCurrency'], 'String');
            }
            if (data.hasOwnProperty('displayAmount')) {
                obj['displayAmount'] = ApiClient.convertToType(data['displayAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NetworkFeeDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NetworkFeeDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paidCurrency'] && !(typeof data['paidCurrency'] === 'string' || data['paidCurrency'] instanceof String)) {
            throw new Error("Expected the field `paidCurrency` to be a primitive type in the JSON string but got " + data['paidCurrency']);
        }
        // ensure the json data is a string
        if (data['displayCurrency'] && !(typeof data['displayCurrency'] === 'string' || data['displayCurrency'] instanceof String)) {
            throw new Error("Expected the field `displayCurrency` to be a primitive type in the JSON string but got " + data['displayCurrency']);
        }

        return true;
    }


}



/**
 * @member {String} paidCurrency
 */
NetworkFeeDto.prototype['paidCurrency'] = undefined;

/**
 * @member {Number} paidAmount
 */
NetworkFeeDto.prototype['paidAmount'] = undefined;

/**
 * @member {String} displayCurrency
 */
NetworkFeeDto.prototype['displayCurrency'] = undefined;

/**
 * @member {Number} displayAmount
 */
NetworkFeeDto.prototype['displayAmount'] = undefined;






export default NetworkFeeDto;

