/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountMethodDto from './AccountMethodDto';

/**
 * The PayInMethodDto model module.
 * @module model/PayInMethodDto
 * @version 1.0.1
 */
class PayInMethodDto {
    /**
     * Constructs a new <code>PayInMethodDto</code>.
     * @alias module:model/PayInMethodDto
     */
    constructor() { 
        
        PayInMethodDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayInMethodDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayInMethodDto} obj Optional instance to populate.
     * @return {module:model/PayInMethodDto} The populated <code>PayInMethodDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayInMethodDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('settlementCurrency')) {
                obj['settlementCurrency'] = ApiClient.convertToType(data['settlementCurrency'], 'String');
            }
            if (data.hasOwnProperty('requestedCurrency')) {
                obj['requestedCurrency'] = ApiClient.convertToType(data['requestedCurrency'], 'String');
            }
            if (data.hasOwnProperty('estimatedExchangeRate')) {
                obj['estimatedExchangeRate'] = ApiClient.convertToType(data['estimatedExchangeRate'], 'Number');
            }
            if (data.hasOwnProperty('accountMethods')) {
                obj['accountMethods'] = ApiClient.convertToType(data['accountMethods'], [AccountMethodDto]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayInMethodDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayInMethodDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['settlementCurrency'] && !(typeof data['settlementCurrency'] === 'string' || data['settlementCurrency'] instanceof String)) {
            throw new Error("Expected the field `settlementCurrency` to be a primitive type in the JSON string but got " + data['settlementCurrency']);
        }
        // ensure the json data is a string
        if (data['requestedCurrency'] && !(typeof data['requestedCurrency'] === 'string' || data['requestedCurrency'] instanceof String)) {
            throw new Error("Expected the field `requestedCurrency` to be a primitive type in the JSON string but got " + data['requestedCurrency']);
        }
        if (data['accountMethods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accountMethods'])) {
                throw new Error("Expected the field `accountMethods` to be an array in the JSON data but got " + data['accountMethods']);
            }
            // validate the optional field `accountMethods` (array)
            for (const item of data['accountMethods']) {
                AccountMethodDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * The ID fo the pay in method.
 * @member {Number} id
 */
PayInMethodDto.prototype['id'] = undefined;

/**
 * The code of the payin.
 * @member {String} code
 */
PayInMethodDto.prototype['code'] = undefined;

/**
 * The settlement currency of the pay in.
 * @member {String} settlementCurrency
 */
PayInMethodDto.prototype['settlementCurrency'] = undefined;

/**
 * The requested currency of the pay in.
 * @member {String} requestedCurrency
 */
PayInMethodDto.prototype['requestedCurrency'] = undefined;

/**
 * The estimated exchange rate of the pay in.
 * @member {Number} estimatedExchangeRate
 */
PayInMethodDto.prototype['estimatedExchangeRate'] = undefined;

/**
 * @member {Array.<module:model/AccountMethodDto>} accountMethods
 */
PayInMethodDto.prototype['accountMethods'] = undefined;






export default PayInMethodDto;

