/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PayInDetailDto model module.
 * @module model/PayInDetailDto
 * @version 1.0.1
 */
class PayInDetailDto {
    /**
     * Constructs a new <code>PayInDetailDto</code>.
     * The payment in details, only needed when \&quot;type\&quot; is IN.
     * @alias module:model/PayInDetailDto
     * @param currency {String} Crypto currency that customer must pay in, will return that address in redirectURL.
     */
    constructor(currency) { 
        
        PayInDetailDto.initialize(this, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency) { 
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>PayInDetailDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayInDetailDto} obj Optional instance to populate.
     * @return {module:model/PayInDetailDto} The populated <code>PayInDetailDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayInDetailDto();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayInDetailDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayInDetailDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PayInDetailDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

PayInDetailDto.RequiredProperties = ["currency"];

/**
 * Crypto currency that customer must pay in, will return that address in redirectURL.
 * @member {String} currency
 */
PayInDetailDto.prototype['currency'] = undefined;






export default PayInDetailDto;

