/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Form from './Form';

/**
 * The PayInInstruction model module.
 * @module model/PayInInstruction
 * @version 1.0.1
 */
class PayInInstruction {
    /**
     * Constructs a new <code>PayInInstruction</code>.
     * @alias module:model/PayInInstruction
     */
    constructor() { 
        
        PayInInstruction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayInInstruction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayInInstruction} obj Optional instance to populate.
     * @return {module:model/PayInInstruction} The populated <code>PayInInstruction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayInInstruction();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('form')) {
                obj['form'] = Form.constructFromObject(data['form']);
            }
            if (data.hasOwnProperty('redirectUrl')) {
                obj['redirectUrl'] = ApiClient.convertToType(data['redirectUrl'], 'String');
            }
            if (data.hasOwnProperty('displayParameters')) {
                obj['displayParameters'] = ApiClient.convertToType(data['displayParameters'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayInInstruction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayInInstruction</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `form`
        if (data['form']) { // data not null
          Form.validateJSON(data['form']);
        }
        // ensure the json data is a string
        if (data['redirectUrl'] && !(typeof data['redirectUrl'] === 'string' || data['redirectUrl'] instanceof String)) {
            throw new Error("Expected the field `redirectUrl` to be a primitive type in the JSON string but got " + data['redirectUrl']);
        }

        return true;
    }


}



/**
 * @member {module:model/PayInInstruction.ActionEnum} action
 */
PayInInstruction.prototype['action'] = undefined;

/**
 * @member {module:model/Form} form
 */
PayInInstruction.prototype['form'] = undefined;

/**
 * @member {String} redirectUrl
 */
PayInInstruction.prototype['redirectUrl'] = undefined;

/**
 * @member {Object} displayParameters
 */
PayInInstruction.prototype['displayParameters'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
PayInInstruction['ActionEnum'] = {

    /**
     * value: "REDIRECT"
     * @const
     */
    "REDIRECT": "REDIRECT",

    /**
     * value: "FORM"
     * @const
     */
    "FORM": "FORM",

    /**
     * value: "DISPLAY"
     * @const
     */
    "DISPLAY": "DISPLAY",

    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE"
};



export default PayInInstruction;

