/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FormDto from './FormDto';

/**
 * The PayInInstructionDto model module.
 * @module model/PayInInstructionDto
 * @version 1.0.1
 */
class PayInInstructionDto {
    /**
     * Constructs a new <code>PayInInstructionDto</code>.
     * @alias module:model/PayInInstructionDto
     */
    constructor() { 
        
        PayInInstructionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayInInstructionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayInInstructionDto} obj Optional instance to populate.
     * @return {module:model/PayInInstructionDto} The populated <code>PayInInstructionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayInInstructionDto();

            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('form')) {
                obj['form'] = FormDto.constructFromObject(data['form']);
            }
            if (data.hasOwnProperty('redirectUrl')) {
                obj['redirectUrl'] = ApiClient.convertToType(data['redirectUrl'], 'String');
            }
            if (data.hasOwnProperty('displayParameters')) {
                obj['displayParameters'] = ApiClient.convertToType(data['displayParameters'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayInInstructionDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayInInstructionDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['action'] && !(typeof data['action'] === 'string' || data['action'] instanceof String)) {
            throw new Error("Expected the field `action` to be a primitive type in the JSON string but got " + data['action']);
        }
        // validate the optional field `form`
        if (data['form']) { // data not null
          FormDto.validateJSON(data['form']);
        }
        // ensure the json data is a string
        if (data['redirectUrl'] && !(typeof data['redirectUrl'] === 'string' || data['redirectUrl'] instanceof String)) {
            throw new Error("Expected the field `redirectUrl` to be a primitive type in the JSON string but got " + data['redirectUrl']);
        }

        return true;
    }


}



/**
 * The pay in action.
 * @member {module:model/PayInInstructionDto.ActionEnum} action
 */
PayInInstructionDto.prototype['action'] = undefined;

/**
 * @member {module:model/FormDto} form
 */
PayInInstructionDto.prototype['form'] = undefined;

/**
 * The pay in instruction redirect code.
 * @member {String} redirectUrl
 */
PayInInstructionDto.prototype['redirectUrl'] = undefined;

/**
 * @member {Object} displayParameters
 */
PayInInstructionDto.prototype['displayParameters'] = undefined;





/**
 * Allowed values for the <code>action</code> property.
 * @enum {String}
 * @readonly
 */
PayInInstructionDto['ActionEnum'] = {

    /**
     * value: "REDIRECT"
     * @const
     */
    "REDIRECT": "REDIRECT",

    /**
     * value: "FORM"
     * @const
     */
    "FORM": "FORM",

    /**
     * value: "DISPLAY"
     * @const
     */
    "DISPLAY": "DISPLAY",

    /**
     * value: "NONE"
     * @const
     */
    "NONE": "NONE"
};



export default PayInInstructionDto;

