/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentStatusDto.
* @enum {}
* @readonly
*/
export default class PaymentStatusDto {
    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    
        /**
         * value: "PROCESSING"
         * @const
         */
        "PROCESSING" = "PROCESSING";

    
        /**
         * value: "CANCELLED"
         * @const
         */
        "CANCELLED" = "CANCELLED";

    
        /**
         * value: "COMPLETE"
         * @const
         */
        "COMPLETE" = "COMPLETE";

    
        /**
         * value: "UNDERPAID"
         * @const
         */
        "UNDERPAID" = "UNDERPAID";

    
        /**
         * value: "OVERPAID"
         * @const
         */
        "OVERPAID" = "OVERPAID";

    
        /**
         * value: "EXPIRED"
         * @const
         */
        "EXPIRED" = "EXPIRED";

    

    /**
    * Returns a <code>PaymentStatusDto</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentStatusDto} The enum <code>PaymentStatusDto</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

