/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountMethod from './AccountMethod';

/**
 * The PayOutMethod model module.
 * @module model/PayOutMethod
 * @version 1.0.1
 */
class PayOutMethod {
    /**
     * Constructs a new <code>PayOutMethod</code>.
     * @alias module:model/PayOutMethod
     */
    constructor() { 
        
        PayOutMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayOutMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayOutMethod} obj Optional instance to populate.
     * @return {module:model/PayOutMethod} The populated <code>PayOutMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayOutMethod();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('accountMethods')) {
                obj['accountMethods'] = ApiClient.convertToType(data['accountMethods'], [AccountMethod]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayOutMethod</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayOutMethod</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        if (data['accountMethods']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['accountMethods'])) {
                throw new Error("Expected the field `accountMethods` to be an array in the JSON data but got " + data['accountMethods']);
            }
            // validate the optional field `accountMethods` (array)
            for (const item of data['accountMethods']) {
                AccountMethod.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
PayOutMethod.prototype['id'] = undefined;

/**
 * @member {String} code
 */
PayOutMethod.prototype['code'] = undefined;

/**
 * @member {String} currency
 */
PayOutMethod.prototype['currency'] = undefined;

/**
 * @member {Array.<module:model/AccountMethod>} accountMethods
 */
PayOutMethod.prototype['accountMethods'] = undefined;






export default PayOutMethod;

