/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PayOutInstructionDto model module.
 * @module model/PayOutInstructionDto
 * @version 1.0.1
 */
class PayOutInstructionDto {
    /**
     * Constructs a new <code>PayOutInstructionDto</code>.
     * @alias module:model/PayOutInstructionDto
     */
    constructor() { 
        
        PayOutInstructionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayOutInstructionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayOutInstructionDto} obj Optional instance to populate.
     * @return {module:model/PayOutInstructionDto} The populated <code>PayOutInstructionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayOutInstructionDto();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayOutInstructionDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayOutInstructionDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}



/**
 * The pay out instruction code.
 * @member {String} code
 */
PayOutInstructionDto.prototype['code'] = undefined;

/**
 * The pay out instruction currency.
 * @member {String} currency
 */
PayOutInstructionDto.prototype['currency'] = undefined;






export default PayOutInstructionDto;

