/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuoteRequest model module.
 * @module model/QuoteRequest
 * @version 1.0.1
 */
class QuoteRequest {
    /**
     * Constructs a new <code>QuoteRequest</code>.
     * @alias module:model/QuoteRequest
     * @param from {String} 
     * @param to {String} 
     * @param fromWallet {Number} 
     * @param useMinimum {Boolean} 
     * @param useMaximum {Boolean} 
     * @param toWallet {Number} 
     * @param amountIn {Number} 
     * @param payInMethod {String} 
     * @param payOutMethod {String} 
     */
    constructor(from, to, fromWallet, useMinimum, useMaximum, toWallet, amountIn, payInMethod, payOutMethod) { 
        
        QuoteRequest.initialize(this, from, to, fromWallet, useMinimum, useMaximum, toWallet, amountIn, payInMethod, payOutMethod);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, from, to, fromWallet, useMinimum, useMaximum, toWallet, amountIn, payInMethod, payOutMethod) { 
        obj['from'] = from || 'EUR';
        obj['to'] = to || 'USDC';
        obj['fromWallet'] = fromWallet || 3598236;
        obj['useMinimum'] = useMinimum || false;
        obj['useMaximum'] = useMaximum || false;
        obj['toWallet'] = toWallet || 3598514;
        obj['amountIn'] = amountIn || 10;
        obj['payInMethod'] = payInMethod || 'wallet';
        obj['payOutMethod'] = payOutMethod || 'wallet';
    }

    /**
     * Constructs a <code>QuoteRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteRequest} obj Optional instance to populate.
     * @return {module:model/QuoteRequest} The populated <code>QuoteRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteRequest();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
            if (data.hasOwnProperty('fromWallet')) {
                obj['fromWallet'] = ApiClient.convertToType(data['fromWallet'], 'Number');
            }
            if (data.hasOwnProperty('useMinimum')) {
                obj['useMinimum'] = ApiClient.convertToType(data['useMinimum'], 'Boolean');
            }
            if (data.hasOwnProperty('useMaximum')) {
                obj['useMaximum'] = ApiClient.convertToType(data['useMaximum'], 'Boolean');
            }
            if (data.hasOwnProperty('toWallet')) {
                obj['toWallet'] = ApiClient.convertToType(data['toWallet'], 'Number');
            }
            if (data.hasOwnProperty('amountIn')) {
                obj['amountIn'] = ApiClient.convertToType(data['amountIn'], 'Number');
            }
            if (data.hasOwnProperty('payInMethod')) {
                obj['payInMethod'] = ApiClient.convertToType(data['payInMethod'], 'String');
            }
            if (data.hasOwnProperty('payOutMethod')) {
                obj['payOutMethod'] = ApiClient.convertToType(data['payOutMethod'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuoteRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['from'] && !(typeof data['from'] === 'string' || data['from'] instanceof String)) {
            throw new Error("Expected the field `from` to be a primitive type in the JSON string but got " + data['from']);
        }
        // ensure the json data is a string
        if (data['to'] && !(typeof data['to'] === 'string' || data['to'] instanceof String)) {
            throw new Error("Expected the field `to` to be a primitive type in the JSON string but got " + data['to']);
        }
        // ensure the json data is a string
        if (data['payInMethod'] && !(typeof data['payInMethod'] === 'string' || data['payInMethod'] instanceof String)) {
            throw new Error("Expected the field `payInMethod` to be a primitive type in the JSON string but got " + data['payInMethod']);
        }
        // ensure the json data is a string
        if (data['payOutMethod'] && !(typeof data['payOutMethod'] === 'string' || data['payOutMethod'] instanceof String)) {
            throw new Error("Expected the field `payOutMethod` to be a primitive type in the JSON string but got " + data['payOutMethod']);
        }

        return true;
    }


}

QuoteRequest.RequiredProperties = ["from", "to", "fromWallet", "useMinimum", "useMaximum", "toWallet", "amountIn", "payInMethod", "payOutMethod"];

/**
 * @member {String} from
 * @default 'EUR'
 */
QuoteRequest.prototype['from'] = 'EUR';

/**
 * @member {String} to
 * @default 'USDC'
 */
QuoteRequest.prototype['to'] = 'USDC';

/**
 * @member {Number} fromWallet
 * @default 3598236
 */
QuoteRequest.prototype['fromWallet'] = 3598236;

/**
 * @member {Boolean} useMinimum
 * @default false
 */
QuoteRequest.prototype['useMinimum'] = false;

/**
 * @member {Boolean} useMaximum
 * @default false
 */
QuoteRequest.prototype['useMaximum'] = false;

/**
 * @member {Number} toWallet
 * @default 3598514
 */
QuoteRequest.prototype['toWallet'] = 3598514;

/**
 * @member {Number} amountIn
 * @default 10
 */
QuoteRequest.prototype['amountIn'] = 10;

/**
 * @member {String} payInMethod
 * @default 'wallet'
 */
QuoteRequest.prototype['payInMethod'] = 'wallet';

/**
 * @member {String} payOutMethod
 * @default 'wallet'
 */
QuoteRequest.prototype['payOutMethod'] = 'wallet';






export default QuoteRequest;

