/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServerErrorDto model module.
 * @module model/ServerErrorDto
 * @version 1.0.1
 */
class ServerErrorDto {
    /**
     * Constructs a new <code>ServerErrorDto</code>.
     * Error object shared when an exception or error is encountered
     * @alias module:model/ServerErrorDto
     * @param code {String} this is used to get internationalisation translation
     * @param message {String} exception message
     */
    constructor(code, message) { 
        
        ServerErrorDto.initialize(this, code, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, message) { 
        obj['code'] = code;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ServerErrorDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServerErrorDto} obj Optional instance to populate.
     * @return {module:model/ServerErrorDto} The populated <code>ServerErrorDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerErrorDto();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServerErrorDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServerErrorDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ServerErrorDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

ServerErrorDto.RequiredProperties = ["code", "message"];

/**
 * this is used to get internationalisation translation
 * @member {String} code
 */
ServerErrorDto.prototype['code'] = undefined;

/**
 * exception message
 * @member {String} message
 */
ServerErrorDto.prototype['message'] = undefined;






export default ServerErrorDto;

