/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationErrorDto model module.
 * @module model/ValidationErrorDto
 * @version 1.0.1
 */
class ValidationErrorDto {
    /**
     * Constructs a new <code>ValidationErrorDto</code>.
     * Error object shared when an exception or error is encountered
     * @alias module:model/ValidationErrorDto
     * @param code {String} this is used to get internationalisation translation
     * @param parameter {String} input that is causing the error
     * @param message {String} exception message
     */
    constructor(code, parameter, message) { 
        
        ValidationErrorDto.initialize(this, code, parameter, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, parameter, message) { 
        obj['code'] = code;
        obj['parameter'] = parameter;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>ValidationErrorDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidationErrorDto} obj Optional instance to populate.
     * @return {module:model/ValidationErrorDto} The populated <code>ValidationErrorDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationErrorDto();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('parameter')) {
                obj['parameter'] = ApiClient.convertToType(data['parameter'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidationErrorDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidationErrorDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ValidationErrorDto.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['parameter'] && !(typeof data['parameter'] === 'string' || data['parameter'] instanceof String)) {
            throw new Error("Expected the field `parameter` to be a primitive type in the JSON string but got " + data['parameter']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

ValidationErrorDto.RequiredProperties = ["code", "parameter", "message"];

/**
 * this is used to get internationalisation translation
 * @member {String} code
 */
ValidationErrorDto.prototype['code'] = undefined;

/**
 * input that is causing the error
 * @member {String} parameter
 */
ValidationErrorDto.prototype['parameter'] = undefined;

/**
 * exception message
 * @member {String} message
 */
ValidationErrorDto.prototype['message'] = undefined;






export default ValidationErrorDto;

