/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.CurrencyFiat();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CurrencyFiat', function() {
    it('should create an instance of CurrencyFiat', function() {
      // uncomment below and update the code to test CurrencyFiat
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be.a(BvnkApiEndpoints.CurrencyFiat);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property depositFee (base name: "depositFee")', function() {
      // uncomment below and update the code to test the property depositFee
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property fiat (base name: "fiat")', function() {
      // uncomment below and update the code to test the property fiat
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property icon (base name: "icon")', function() {
      // uncomment below and update the code to test the property icon
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property options (base name: "options")', function() {
      // uncomment below and update the code to test the property options
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property pricePrecision (base name: "pricePrecision")', function() {
      // uncomment below and update the code to test the property pricePrecision
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property protocols (base name: "protocols")', function() {
      // uncomment below and update the code to test the property protocols
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property quantityPrecision (base name: "quantityPrecision")', function() {
      // uncomment below and update the code to test the property quantityPrecision
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property supportsDeposits (base name: "supportsDeposits")', function() {
      // uncomment below and update the code to test the property supportsDeposits
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property supportsWithdrawals (base name: "supportsWithdrawals")', function() {
      // uncomment below and update the code to test the property supportsWithdrawals
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property withdrawalFee (base name: "withdrawalFee")', function() {
      // uncomment below and update the code to test the property withdrawalFee
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

    it('should have the property withdrawalParameters (base name: "withdrawalParameters")', function() {
      // uncomment below and update the code to test the property withdrawalParameters
      //var instance = new BvnkApiEndpoints.CurrencyFiat();
      //expect(instance).to.be();
    });

  });

}));
