/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantChannelPaymentDto', function() {
    it('should create an instance of MerchantChannelPaymentDto', function() {
      // uncomment below and update the code to test MerchantChannelPaymentDto
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.MerchantChannelPaymentDto);
    });

    it('should have the property channelId (base name: "channelId")', function() {
      // uncomment below and update the code to test the property channelId
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property merchantDisplayName (base name: "merchantDisplayName")', function() {
      // uncomment below and update the code to test the property merchantDisplayName
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property hash (base name: "hash")', function() {
      // uncomment below and update the code to test the property hash
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property tag (base name: "tag")', function() {
      // uncomment below and update the code to test the property tag
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property paidCurrency (base name: "paidCurrency")', function() {
      // uncomment below and update the code to test the property paidCurrency
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property displayCurrency (base name: "displayCurrency")', function() {
      // uncomment below and update the code to test the property displayCurrency
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property walletCurrency (base name: "walletCurrency")', function() {
      // uncomment below and update the code to test the property walletCurrency
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property feeCurrency (base name: "feeCurrency")', function() {
      // uncomment below and update the code to test the property feeCurrency
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property paidAmount (base name: "paidAmount")', function() {
      // uncomment below and update the code to test the property paidAmount
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property displayAmount (base name: "displayAmount")', function() {
      // uncomment below and update the code to test the property displayAmount
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property walletAmount (base name: "walletAmount")', function() {
      // uncomment below and update the code to test the property walletAmount
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property feeAmount (base name: "feeAmount")', function() {
      // uncomment below and update the code to test the property feeAmount
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property exchangeRate (base name: "exchangeRate")', function() {
      // uncomment below and update the code to test the property exchangeRate
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property displayRate (base name: "displayRate")', function() {
      // uncomment below and update the code to test the property displayRate
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property risk (base name: "risk")', function() {
      // uncomment below and update the code to test the property risk
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property sources (base name: "sources")', function() {
      // uncomment below and update the code to test the property sources
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property networkFee (base name: "networkFee")', function() {
      // uncomment below and update the code to test the property networkFee
      //var instance = new BvnkApiEndpoints.MerchantChannelPaymentDto();
      //expect(instance).to.be();
    });

  });

}));
