/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.MerchantDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MerchantDto', function() {
    it('should create an instance of MerchantDto', function() {
      // uncomment below and update the code to test MerchantDto
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.MerchantDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property secret (base name: "secret")', function() {
      // uncomment below and update the code to test the property secret
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property webhookUrl (base name: "webhookUrl")', function() {
      // uncomment below and update the code to test the property webhookUrl
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property autoConvertInvalidPayments (base name: "autoConvertInvalidPayments")', function() {
      // uncomment below and update the code to test the property autoConvertInvalidPayments
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property defaultExpiryMinutes (base name: "defaultExpiryMinutes")', function() {
      // uncomment below and update the code to test the property defaultExpiryMinutes
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property webhookVersion (base name: "webhookVersion")', function() {
      // uncomment below and update the code to test the property webhookVersion
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property wallet (base name: "wallet")', function() {
      // uncomment below and update the code to test the property wallet
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

    it('should have the property emailRecipients (base name: "emailRecipients")', function() {
      // uncomment below and update the code to test the property emailRecipients
      //var instance = new BvnkApiEndpoints.MerchantDto();
      //expect(instance).to.be();
    });

  });

}));
