/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.NetworkFeeDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NetworkFeeDto', function() {
    it('should create an instance of NetworkFeeDto', function() {
      // uncomment below and update the code to test NetworkFeeDto
      //var instance = new BvnkApiEndpoints.NetworkFeeDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.NetworkFeeDto);
    });

    it('should have the property paidCurrency (base name: "paidCurrency")', function() {
      // uncomment below and update the code to test the property paidCurrency
      //var instance = new BvnkApiEndpoints.NetworkFeeDto();
      //expect(instance).to.be();
    });

    it('should have the property paidAmount (base name: "paidAmount")', function() {
      // uncomment below and update the code to test the property paidAmount
      //var instance = new BvnkApiEndpoints.NetworkFeeDto();
      //expect(instance).to.be();
    });

    it('should have the property displayCurrency (base name: "displayCurrency")', function() {
      // uncomment below and update the code to test the property displayCurrency
      //var instance = new BvnkApiEndpoints.NetworkFeeDto();
      //expect(instance).to.be();
    });

    it('should have the property displayAmount (base name: "displayAmount")', function() {
      // uncomment below and update the code to test the property displayAmount
      //var instance = new BvnkApiEndpoints.NetworkFeeDto();
      //expect(instance).to.be();
    });

  });

}));
