/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.QuoteRequestDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuoteRequestDto', function() {
    it('should create an instance of QuoteRequestDto', function() {
      // uncomment below and update the code to test QuoteRequestDto
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.QuoteRequestDto);
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property fromWallet (base name: "fromWallet")', function() {
      // uncomment below and update the code to test the property fromWallet
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property useMinimum (base name: "useMinimum")', function() {
      // uncomment below and update the code to test the property useMinimum
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property useMaximum (base name: "useMaximum")', function() {
      // uncomment below and update the code to test the property useMaximum
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property toWallet (base name: "toWallet")', function() {
      // uncomment below and update the code to test the property toWallet
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property amountIn (base name: "amountIn")', function() {
      // uncomment below and update the code to test the property amountIn
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property payInMethod (base name: "payInMethod")', function() {
      // uncomment below and update the code to test the property payInMethod
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

    it('should have the property payOutMethod (base name: "payOutMethod")', function() {
      // uncomment below and update the code to test the property payOutMethod
      //var instance = new BvnkApiEndpoints.QuoteRequestDto();
      //expect(instance).to.be();
    });

  });

}));
