/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, and digital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.QuoteDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuoteDto', function() {
    it('should create an instance of QuoteDto', function() {
      // uncomment below and update the code to test QuoteDto
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.QuoteDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property from (base name: "from")', function() {
      // uncomment below and update the code to test the property from
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property to (base name: "to")', function() {
      // uncomment below and update the code to test the property to
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property amountIn (base name: "amountIn")', function() {
      // uncomment below and update the code to test the property amountIn
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property amountDue (base name: "amountDue")', function() {
      // uncomment below and update the code to test the property amountDue
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property amountOut (base name: "amountOut")', function() {
      // uncomment below and update the code to test the property amountOut
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property quoteStatus (base name: "quoteStatus")', function() {
      // uncomment below and update the code to test the property quoteStatus
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property paymentStatus (base name: "paymentStatus")', function() {
      // uncomment below and update the code to test the property paymentStatus
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property acceptanceExpiryDate (base name: "acceptanceExpiryDate")', function() {
      // uncomment below and update the code to test the property acceptanceExpiryDate
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property acceptanceDate (base name: "acceptanceDate")', function() {
      // uncomment below and update the code to test the property acceptanceDate
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property paymentExpiryDate (base name: "paymentExpiryDate")', function() {
      // uncomment below and update the code to test the property paymentExpiryDate
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property paymentReceiptDate (base name: "paymentReceiptDate")', function() {
      // uncomment below and update the code to test the property paymentReceiptDate
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property payInLegs (base name: "payInLegs")', function() {
      // uncomment below and update the code to test the property payInLegs
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property payInMethod (base name: "payInMethod")', function() {
      // uncomment below and update the code to test the property payInMethod
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property payOutMethod (base name: "payOutMethod")', function() {
      // uncomment below and update the code to test the property payOutMethod
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property payOutInstruction (base name: "payOutInstruction")', function() {
      // uncomment below and update the code to test the property payOutInstruction
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property payInInstruction (base name: "payInInstruction")', function() {
      // uncomment below and update the code to test the property payInInstruction
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property usePayInMethod (base name: "usePayInMethod")', function() {
      // uncomment below and update the code to test the property usePayInMethod
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property usePayOutMethod (base name: "usePayOutMethod")', function() {
      // uncomment below and update the code to test the property usePayOutMethod
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property fee (base name: "fee")', function() {
      // uncomment below and update the code to test the property fee
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property processingFee (base name: "processingFee")', function() {
      // uncomment below and update the code to test the property processingFee
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property netPrice (base name: "netPrice")', function() {
      // uncomment below and update the code to test the property netPrice
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property grossPrice (base name: "grossPrice")', function() {
      // uncomment below and update the code to test the property grossPrice
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property amountInGross (base name: "amountInGross")', function() {
      // uncomment below and update the code to test the property amountInGross
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property amountInNet (base name: "amountInNet")', function() {
      // uncomment below and update the code to test the property amountInNet
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property fees (base name: "fees")', function() {
      // uncomment below and update the code to test the property fees
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

    it('should have the property lastUpdated (base name: "lastUpdated")', function() {
      // uncomment below and update the code to test the property lastUpdated
      //var instance = new BvnkApiEndpoints.QuoteDto();
      //expect(instance).to.be();
    });

  });

}));
