/**
 * BVNK API Endpoints
 * The BVNK API is designed to facilitate seamless and secure transactions including payments, channels, anddigital wallet transactions.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BvnkApiEndpoints);
  }
}(this, function(expect, BvnkApiEndpoints) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BvnkApiEndpoints.SummaryPaymentDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SummaryPaymentDto', function() {
    it('should create an instance of SummaryPaymentDto', function() {
      // uncomment below and update the code to test SummaryPaymentDto
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be.a(BvnkApiEndpoints.SummaryPaymentDto);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property merchantDisplayName (base name: "merchantDisplayName")', function() {
      // uncomment below and update the code to test the property merchantDisplayName
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiryDate")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property quoteExpiryDate (base name: "quoteExpiryDate")', function() {
      // uncomment below and update the code to test the property quoteExpiryDate
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property acceptanceExpiryDate (base name: "acceptanceExpiryDate")', function() {
      // uncomment below and update the code to test the property acceptanceExpiryDate
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property quoteStatus (base name: "quoteStatus")', function() {
      // uncomment below and update the code to test the property quoteStatus
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property subType (base name: "subType")', function() {
      // uncomment below and update the code to test the property subType
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property displayCurrency (base name: "displayCurrency")', function() {
      // uncomment below and update the code to test the property displayCurrency
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property walletCurrency (base name: "walletCurrency")', function() {
      // uncomment below and update the code to test the property walletCurrency
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property paidCurrency (base name: "paidCurrency")', function() {
      // uncomment below and update the code to test the property paidCurrency
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property feeCurrency (base name: "feeCurrency")', function() {
      // uncomment below and update the code to test the property feeCurrency
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property displayRate (base name: "displayRate")', function() {
      // uncomment below and update the code to test the property displayRate
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property exchangeRate (base name: "exchangeRate")', function() {
      // uncomment below and update the code to test the property exchangeRate
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property returnUrl (base name: "returnUrl")', function() {
      // uncomment below and update the code to test the property returnUrl
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirectUrl")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property transactions (base name: "transactions")', function() {
      // uncomment below and update the code to test the property transactions
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property refund (base name: "refund")', function() {
      // uncomment below and update the code to test the property refund
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

    it('should have the property refunds (base name: "refunds")', function() {
      // uncomment below and update the code to test the property refunds
      //var instance = new BvnkApiEndpoints.SummaryPaymentDto();
      //expect(instance).to.be();
    });

  });

}));
